# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirdPartySignIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartySignIn
		
    pod 'IQKeyboardManagerSwift'
     pod 'FBSDKLoginKit'
     pod 'Firebase/Core'
     pod 'Firebase/Auth'
     pod 'GoogleSignIn'

  target 'ThirdPartySignInTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThirdPartySignInUITests' do
    # Pods for testing
  end

end
